name: teleconference_app
description: A real-time teleconference application with noise cancellation and speech-to-text features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_webrtc: ^0.9.34
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  flutter_sound: ^9.2.13
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.77.0
  uuid: ^3.0.7
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  ffigen: ^8.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
